### PR TITLE
Fix more typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found a few more.

Remaining ones

```
     11  `additionals` -> `additional`
     13  `dependend` -> `dependent`, `depended`
     19  `targetted` -> `targeted`
```

### CODE REVIEW

**Comment by leoloso** [comment]
Fixed. But kept `additionals`, that's a method name, I like it better like that. (Can add to the ignore list)

**Comment by szepeviktor** [comment]
@leoloso All right.

What about the changes in this PR?

**Comment by leoloso** [comment]
Oh I'm sorry, I only read the PR body, didn't check the files. Reopening.

**Comment by leoloso** [comment]
Thanks @szepeviktor I reverted one word (it was French!), all other were good

**Pull request merged**
